version: '2'

services:
#  bikes-base:
#    build:
#      context: ./src/
#      dockerfile: Dockerfile
#    image: bikes-base:latest

  bikes-api:
    build:
      context: ./src/
      dockerfile: api/Dockerfile
    image: bikes-api:latest
    container_name: bikes-api
    links:
      - postgres:local-bikes-postgres.aveng.us
    ports:
      - 5000:5000
    volumes:
      - ./data/:/srv/data
      - ./src/:/srv/src/
    environment:
      - ENVIRONMENT=dev
      - DATA_ROOT=/srv/data

#  bikes-bikedb:
#    build:
#      context: ./src/
#      dockerfile: bikedb/Dockerfile
#    image: bikes-bikedb:latest
#    container_name: bikes-bikedb
#    volumes:
#      - ./data/:/srv/data
#      - ./src/:/srv/src
#    links:
#      - postgres:local-bikes-postgres.aveng.us
#    environment:
#      - ENVIRONMENT=dev
#      - DATA_ROOT=/srv/data
#      - FLASK_STORAGE=0
#
#    ports:
#        - 3306:3306

    #  bikes-buildui:
#    build:
#      context: ./src/
#      dockerfile: ui/Dockerfile
#    image: bikes-ui:latest
#    container_name: bikes-buildui
#    volumes:
#      - ./data/:/srv/data
#      - ./src/:/srv/src
#    environment:
#      - ENVIRONMENT=dev
#    ports:
#        - 3000:3000

  postgres:
    image: postgres:10.6
    restart: always
    environment:
      - POSTGRES_DB=bikes
      - POSTGRES_USER=wombat
      - POSTGRES_PASSWORD=1wombat2
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
