# Generated by Django 5.0.9 on 2024-10-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='activity_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='params',
            field=models.JSONField(max_length=5000),
        ),
    ]
