# Generated by Django 5.0.9 on 2024-12-27 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_trainingentry_activity_type_alter_season_params'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stravaactivity',
            index=models.Index(fields=['start_datetime_local'], name='bikes_strav_start_d_887b36_idx'),
        ),
        migrations.AddIndex(
            model_name='stravaactivity',
            index=models.Index(fields=['start_datetime'], name='bikes_strav_start_d_6f9fcf_idx'),
        ),
    ]
