name: On PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]


jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::408799413549:role/github-actions-bikes-api
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: lint and test
        run: |
          ./.github/workflows/scripts/build-test-deploy.sh test

#      # uncomment to build and deploy your PR image
#      - name: build and publish
#        env:
#          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          REPOSITORY: flannelcat
#          TASK_FAMILY: rustybrooks-backend-prod-flannelcat-webapi
#          AWS_REGION: us-west-2
#          ECS_CLUSTER: rustybrooks-backend-prod
#          SERVICE_NAME: flannelcat-webapi
#          ENV: dev
#        run: |
#          export IMAGE_TAG="$(date +%Y-%m-%d)-$(echo ${{github.sha}} | cut -c1-8)"
#          ./.github/workflows/scripts/build-test-deploy.sh deploy
